name = "mysite-analytics"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[durable_objects.bindings]]
name = "VISITOR_TRACKER"
class_name = "VisitorTracker"

[[migrations]]
tag = "v1"
new_classes = ["VisitorTracker"]
